# Path: traxgen/traxgen/plates.py
"""Baseplate geometry: which local cells each `LayerKind` is measured to occupy.

Open unknown #3, answered from the corpus on 2026-08-21 and confirmed on the
render channel the same day. A layer does not carry its own extent on the wire
-- it carries a `world_hex_position` and a list of occupied cells -- so "is this
cell on a plate" is not a field to read but a fact to measure. These footprints
are that measurement.

Provenance, regenerated by `scripts/probe_plate_footprint.py` against the
course corpus (`decisions.md` 2026-08-18: binaries stay out of the repo,
reproducibility comes from the committed script): 808 files, 640 parsed, 77
skipped as v2 and 31 as v7 by declared version, 60 further parse failures
recorded rather than swallowed.

**Positive evidence only, in the same sense as the port records.** A position
absent from a footprint has never been observed; across 28,494 BASE_LAYER_PIECE
placements that is strong, and it is still not proof the app forbids it.

The render channel tested the operative half on 2026-08-21 and it held, on
**two cells**: E and SW from BASE_LAYER_PIECE local (0, 1), both port-allowed
and both off the footprint, both rendered inactive. That is what refuted the
port-only model. It is not a rendered survey of the footprint's boundary, and
this module should not be read as one -- "off-plate kills everywhere" is the
model's extrapolation, held at UNMEASURED by `graph.py` exactly like any other.

*Why* it kills stays open unknown #17: the cell may have no plate under it, or
the format may store coordinates inside a canonical window with
`world_hex_position` absorbing the offset. Both readings predict the same thing
here, which is why this module states the footprint and not the reason.

Two structural facts worth having in view, because they are why the corner
matters. `LARGE_LAYER` (19 cells) and `SMALL_LAYER` (7 cells) are hexagons
*centred* on their local origin, so all six neighbours of (0,0) are occupied in
the corpus. `BASE_LAYER_PIECE` (30 cells) is not: its local origin sits on a
boundary with W, SW and SE unobserved in every one of those 28,494 placements.
Every sweep through 2026-08-10 pinned the STARTER at that origin, which is
where the live-direction table's 2-vs-1 asymmetry came from -- see
`graph.py` and `decisions.md` 2026-08-21.

`BASE_LAYER` and `LARGE_GHOST_LAYER` are **unmeasured**, not empty: the corpus
shows zero cells on either, and zero observations of something the corpus may
simply not record means invisible, not absent (`decisions.md` 2026-08-21, "Ask
what the corpus can see"). Asking about them raises rather than answering
`False`.

Sharpened 2026-08-24 (s25) with an instrument that can see an empty layer: the
corpus carries zero `BASE_LAYER` **layers**, not merely zero cells on them, in
all 640 parsed courses (`scripts/probe_plate_arrangement.py`, `kind=` tallies).
The footprint probe above cannot establish that, because it counts kinds from
within `cell_construction_datas` and an empty layer contributes none. The
conclusion is unchanged and the evidence is stronger -- and it is still
positive evidence only.
"""

from __future__ import annotations

from types import MappingProxyType
from typing import TYPE_CHECKING

from traxgen.hex import HexVector
from traxgen.types import LayerKind

if TYPE_CHECKING:
    from collections.abc import Mapping

# Which `LayerKind`s are physical baseplates. Moved here 2026-08-24 (s25) from
# `validator._BASEPLATE_LAYER_KINDS`, which held the only copy; `graph.py`
# cannot import it from there (the validator imports `graph`, so the dependency
# would be circular) and had grown its own narrower copy counting
# `BASE_LAYER_PIECE` alone. Two definitions of "baseplate" in one library, and
# the narrower one was gating connection claims: the certified course plus one
# empty `BASE_LAYER` returned CONNECTED from a record measured on a single
# plate. Enacted before the move, not argued from reading. One definition here,
# imported by both, is what makes that hole un-reintroducible.
#
# The classification itself is unchanged and its rationale is unchanged. The
# Rust source's `layer_height` doc-comment is the source of truth --
# "-0.2 is the layer height for all base plates" -- and the plural "all base
# plates" treats both `BASE_LAYER` and `BASE_LAYER_PIECE` as baseplate
# variants. Physical intuition: legacy full-plate (Core-era) vs modern modular
# tiles (PRO-era). GDZJZA3J3T (PRO-era) has 15 `BASE_LAYER_PIECE` layers and
# zero `BASE_LAYER`. See docs/refs/layer-kinds-and-world-coords.md for the full
# rationale, the alternatives considered, and the when-to-revisit conditions.
# The integration canary (unlimited inventory on GDZJZA3J3T) would catch any
# future fixture that contradicts this treatment -- a sentence that lived beside
# the constant in `validator.py` and travelled with it rather than being lost.
#
# Note this is a *classification*, not a footprint: `BASE_LAYER` is a baseplate
# kind and has no measured footprint (see the module docstring). Membership here
# says what a layer is, not where its cells are, and the two questions have
# different answers for exactly that kind.
BASEPLATE_LAYER_KINDS: frozenset[LayerKind] = frozenset({
    LayerKind.BASE_LAYER,
    LayerKind.BASE_LAYER_PIECE,
})

# Generated by scripts/probe_plate_footprint.py, never hand-typed -- a typed
# list of a measured set is an untested claim wearing a constant's clothes.
MEASURED_FOOTPRINTS: Mapping[LayerKind, frozenset[tuple[int, int]]] = MappingProxyType(
    {
        # BASE_LAYER_PIECE: 30 cells, 28494 placements
        LayerKind.BASE_LAYER_PIECE: frozenset(
            {
                (-6, 4), (-6, 5),
                (-5, 2), (-5, 3), (-5, 4), (-5, 5),
                (-4, 0), (-4, 1), (-4, 2), (-4, 3), (-4, 4), (-4, 5),
                (-3, 0), (-3, 1), (-3, 2), (-3, 3), (-3, 4), (-3, 5),
                (-2, 0), (-2, 1), (-2, 2), (-2, 3), (-2, 4), (-2, 5),
                (-1, 0), (-1, 1), (-1, 2), (-1, 3),
                (0, 0), (0, 1),
            }
        ),
        # LARGE_LAYER: 19 cells, 12668 placements
        LayerKind.LARGE_LAYER: frozenset(
            {
                (-2, 0), (-2, 1), (-2, 2),
                (-1, -1), (-1, 0), (-1, 1), (-1, 2),
                (0, -2), (0, -1), (0, 0), (0, 1), (0, 2),
                (1, -2), (1, -1), (1, 0), (1, 1),
                (2, -2), (2, -1), (2, 0),
            }
        ),
        # SMALL_LAYER: 7 cells, 2959 placements
        LayerKind.SMALL_LAYER: frozenset(
            {
                (-1, 0), (-1, 1),
                (0, -1), (0, 0), (0, 1),
                (1, -1), (1, 0),
            }
        ),
    }
)


# Generated by scripts/probe_plate_arrangement.py against the same corpus, never
# hand-typed, for the same reason as the footprints above. The modal four-plate
# arrangement: 228 of the 241 four-plate courses use exactly this set of world
# positions. Measured as a *set* rather than inferred from four marginal
# frequencies. Of the 11 distinct four-plate sets, **8 are this shape
# translated and 3 are not** -- two are a straight line of four plates
# (normalised ((0,0),(5,0),(10,0),(15,0))) and one is an L. An earlier draft of
# this comment said all the rest were translations; the translation check in
# `report()` was added to make the claim checkable and refuted it on the first
# run (observations #12).
#
# Two further facts from the same scan, both bearing on open unknown #16:
# 599 of 640 parsed courses carry two or more plates, so single-plate is the
# exception in the wild; and **zero** of the 640 show two plates claiming one
# world cell when the footprint above is applied at each `world_hex_position`,
# so `world + local` is a coherent global frame rather than a per-plate
# convenience.
#
# This is a description of what the corpus contains. It is **not** a claim that
# the app requires this arrangement, nor that connection composes across a plate
# boundary -- that is open unknown #17. On the claim side `graph.py` holds every
# multi-plate course at `UNMEASURED`, and since 2026-08-24 (s25) it does so
# without a rule that says to: `MeasuredRun.plate_offsets` records the plate
# layout each campaign ran on, so a course whose layout no campaign had simply
# misses the record. Note the level, because it is where the s24 defect lived:
# `classify_pair` sends only *cross-layer* pairs to UNMEASURED, so a same-plate
# pair on a four-plate course was classified exactly as on a single-plate one
# until the layout became part of the key.
STANDARD_SQUARE: tuple[tuple[int, int], ...] = (
    (0, 0),
    (3, -6),
    (5, 0),
    (8, -6),
)


class UnmeasuredLayerKindError(LookupError):
    """Raised when a layer kind's footprint has never been observed in the corpus."""

    def __init__(self, kind: LayerKind) -> None:
        self.kind = kind
        super().__init__(
            f"{kind.name} has no measured footprint; "
            f"measured kinds: {sorted(k.name for k in MEASURED_FOOTPRINTS)}. "
            "Zero corpus observations means invisible, not absent -- this is a "
            "refusal to answer, not an empty plate. Re-run "
            "scripts/probe_plate_footprint.py against a corpus that contains it."
        )


def plate_footprint(kind: LayerKind) -> frozenset[tuple[int, int]]:
    """The local `(y, x)` cells `kind` is measured to occupy."""
    try:
        return MEASURED_FOOTPRINTS[kind]
    except KeyError:
        raise UnmeasuredLayerKindError(kind) from None


def is_on_plate(kind: LayerKind, local_pos: HexVector) -> bool:
    """Whether `local_pos` is a cell the corpus shows occupied on `kind`.

    Raises `UnmeasuredLayerKindError` for a kind with no measured footprint,
    rather than reporting every one of its cells as off-plate.
    """
    return (local_pos.y, local_pos.x) in plate_footprint(kind)


def plate_available_directions(kind: LayerKind, local_pos: HexVector) -> frozenset[int]:
    """The directions from `local_pos` whose neighbouring cell is on `kind`'s plate.

    The world-fixed half of the connection conjunction (`graph.py`). At
    `BASE_LAYER_PIECE` local (0,0) this is `{E, NE, NW}` -- the plate corner
    that the live-direction table had absorbed without recording.
    """
    footprint = plate_footprint(kind)
    return frozenset(
        d for d in range(6) if _as_key(local_pos.neighbor(d)) in footprint
    )


def _as_key(pos: HexVector) -> tuple[int, int]:
    """A footprint-set key from a hex position."""
    return (pos.y, pos.x)
